### ISSUE TITLE
Create a Lo-fi of the User interface

### ISSUE THREAD

**Issue by Decafoats** [Decafoats/Achilles#2]
We need to create a Lo-fi diagram for our mobile app's AI.

**Comment by AhrasAli** [comment]
File: [Lofi ENSE 400.pdf](https://github.com/Decafoats/Achilles/files/9651145/Lofi.ENSE.400.pdf)

We used pen and paper to lay out our app pages. We then determined the order in which each page would be displayed and what contents to display. We ended our Lo-fi by linking the pages with lines depending on the input the user selects. 

We also discussed consent forms and if the user needs to create an account. 

Lastly, we discuss how the image will be taken from the front end. (Trace the outline of the foot when the user is taking a photo) 


![Image](https://user-images.githubusercontent.com/55845777/192423718-47807024-a8d3-476f-a251-ce01bdc4bf19.png)
